### ISSUE TITLE
reconnection strategies for command line tools

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#333] opened 2019-08-14 14:29 UTC
What strategy is currently implemented in case the `unipept` command can temporarily not connect to the host at the start of a session, or when the connection is temporarily lost during a session. Since some of the sessions will potentially run quite long, we should carefully think about how the command should respond to downtime. Also, how is the user informed about lost analysis data during a session. Most use cases will be non-interactive, so this should also be given some toughts.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/333) by @pdawyndt on Sun May 18 2014 at 14:52._
_Closed by @bmesuere on Wed May 20 2015 at 18:32._

**Comment by bmesuere** [comment] 2019-08-14 14:45
I'll briefly explain what I do now:
- if the request times out -> a message is printed to stderr. We continue with the rest of the input.
- if the request produces an error -> the error is saved in ~/.unipept (with accompanying message to stderr). We continue with the rest of the input.

What I think should be done:
- Log the entire input for with requests failed in a convenient file so it can be easily resumed. 


_[Original comment](https://github.ugent.be/unipept/unipept/issues/333#issuecomment-9836) by ghost on Mon May 19 2014 at 10:53._

**Comment by bmesuere** [comment] 2019-08-14 14:50
Duplicate of unipept/unipept-cli#23


_[Original comment](https://github.ugent.be/unipept/unipept/issues/333#issuecomment-18117) by @bmesuere on Wed May 20 2015 at 18:32._

**Closed** 2019-08-14 15:20 UTC
Labels: /services/cli, migrated, question
