### ISSUE TITLE
add copyright footnotes to images

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#93] opened 2019-08-14 14:24 UTC
add copyright footnote to images generated from the unipept web pages

_[Original issue](https://github.ugent.be/unipept/unipept/issues/93) by @pdawyndt on Sat Oct 06 2012 at 15:56._
_Closed by @bmesuere on Tue Oct 09 2012 at 09:40._

**Comment by bmesuere** [comment] 2019-08-14 14:41
Duplicate of #86


_[Original comment](https://github.ugent.be/unipept/unipept/issues/93#issuecomment-258) by @bmesuere on Tue Oct 09 2012 at 09:40._

**Closed** 2019-08-14 15:01 UTC
Labels: feature, migrated
