### ISSUE TITLE
pass input files as arguments to command line tools

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#262] opened 2019-08-14 14:28 UTC
some commands may have the following signature

```
command [file ...]
```

meaning that they both can read their input from stdin or from one or more files specified as arguments to the function; the latter takes precedence over the former

for example, the `prot2pept` command may be called in the following ways

```
$ prot2pept < seq.fasta
$ prot2pept seq.fasta
$ prot2pept seq1.fasta seq2.fasta seq3.fasta
```

_[Original issue](https://github.ugent.be/unipept/unipept/issues/262) by @pdawyndt on Fri May 02 2014 at 20:07._
_Closed by @bmesuere on Wed May 20 2015 at 18:41._

**Comment by pdawyndt** [comment] 2019-08-14 14:46
I guess this has been resolved by providing the `-i`/`--input option`. Only question remaining is whether it is possible to specify multiple `-i` options to read from multiple files.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/262#issuecomment-9976) by @pdawyndt on Sun Jun 01 2014 at 16:17._

**Comment by bmesuere** [comment] 2019-08-14 14:46
That is possible, and can keep the streaming properties of the commands.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/262#issuecomment-9977) by ghost on Sun Jun 01 2014 at 16:22._

**Comment by bmesuere** [comment] 2019-08-14 14:50
Half implemented and half duplicate of unipept/unipept-cli#29


_[Original comment](https://github.ugent.be/unipept/unipept/issues/262#issuecomment-18120) by @bmesuere on Wed May 20 2015 at 18:41._

**Closed** 2019-08-14 15:14 UTC
Labels: /services/cli, duplicate, feature, migrated
