### ISSUE TITLE
load samples from datasets page

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#90] opened 2019-08-14 14:24 UTC
on the datasets page it should be possible to load a particular data set in the multi-peptide analysis window

_[Original issue](https://github.ugent.be/unipept/unipept/issues/90) by @pdawyndt on Sat Oct 06 2012 at 15:54._
_Closed by @bmesuere on Tue Oct 09 2012 at 09:39._

**Comment by bmesuere** [comment] 2019-08-14 14:41
Duplicate of #59


_[Original comment](https://github.ugent.be/unipept/unipept/issues/90#issuecomment-257) by @bmesuere on Tue Oct 09 2012 at 09:39._

**Closed** 2019-08-14 15:01 UTC
Labels: feature, migrated
